### ISSUE TITLE
Missing pin wiring

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/ZenDriver#12]
GPIO 12, 14 27 and 13 are not wired causing both motor drivers and both encoders to not work.

**Comment by acamilo** [comment]
12 14 and 27 where disconnected. 13 is routed properly.

**Comment by madhephaestus** [comment]
then there is something else wrong with the left driver

**Comment by acamilo** [comment]
I suspect you have a bad solder joint on your unit.
the left driver on my unit is working well.
I recomend flux and reflow with hot air for your board

**Comment by acamilo** [comment]
These pins have been reconnected in the schematic
