### ISSUE TITLE
Pin 23 on the SPI connector conflicts with I2C

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/ZenDriver#3]
Using a Thing, 23 is used as the SDA (typically). Which means it conflict with the pin in the SPI connector.

Not sure why there are five pins in the SPI connector.

GPIO2 doesn't exist on the Thing, so then there's no CS pin there.

**Comment by acamilo** [comment]
Kevin asked me to break out GPIO2 and I stuck it on that header.

JP1 will swap between 23 and 21. It's a cuttable and solderable jumper.
Should we make it a DIP switch or something?

**Comment by gcl8a** [comment]
I’d use a DIP. In the event we go back and forth.

**Comment by acamilo** [comment]
Ok, I can swap it out.
