### ISSUE TITLE
Jumper wire near voltage regulators?

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/ZenDriver#30]
I assume this little jumper wire near the voltage regulators is being replaced with a trace, yes?

**Comment by acamilo** [comment]
yes, that was a manufacturing defect. We got a partial refund because of it.
![image](https://user-images.githubusercontent.com/2826967/102258425-ec690e80-3edb-11eb-85d8-16f75a83491a.png)
![image](https://user-images.githubusercontent.com/2826967/102258436-ef63ff00-3edb-11eb-9e48-5a2bed220970.png)
