### ISSUE TITLE
Add the line driver chip to Serial2 (pins 16 and 17) using Pin 19 as line enable for the LewanSoul motors

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/ZenDriver#8]
I tested this out with the baby yoda and it worked well. It would allow us to add arbitrarily more motors to the 1001 kits using the bus style connections. 

Add 3 sockets to the bus to distribute the current load.

**Comment by acamilo** [comment]
Is there another set of pins we can use?
16 and 17 are going to the LIDAR connector.  It would be nice to have both lidar and LS motors.

**Comment by madhephaestus** [comment]
same pins for the same reason, its the only availible hardware serial port

**Comment by acamilo** [comment]
You can use the GPIO matrix to route the uart pins to free GPIO.

**Comment by acamilo** [comment]
See chapter 5 of this document
https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf

**Comment by acamilo** [comment]
You might be able to mux TX and RX as well without an external chip.

**Comment by madhephaestus** [comment]
yeah i was looking into that, ill try it on Yoda

**Comment by acamilo** [comment]
What power rail should I use? 5v or battery?

**Comment by madhephaestus** [comment]
battery

**Comment by acamilo** [comment]
Added 3 lewansoul connectors to rev 2. No buffer, directly connected to GPIO33
