### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/ZenDriver#9]
Reverse the order of the ultrasonic pins (w.r.t. V2) so that the ultrasonic can be put in the socket and faces forward.

Add a three-pin socket for an IR remote detector (e.g., https://www.pololu.com/product/2462). Would need to go to a digital pin with an external interrupt. (I used pin 34 to test, but that is reserved for the servo feedback, yes?)

**Comment by acamilo** [comment]
The HC-04 pinout should be correct.
https://media.digikey.com/Photos/Adafruit%20Industries%20LLC/MFG_3942.jpg

**Comment by acamilo** [comment]
Added socket for IR Detector.
